document.writeln("<div id=\'navbar\' class=\'navbar navbar-default ace-save-state\'>");
document.writeln("			<div class=\'navbar-container ace-save-state\' id=\'navbar-container\' style=\'padding-left:0;padding-right:0;\'>");
document.writeln("				<button type=\'button\' class=\'navbar-toggle menu-toggler pull-left\' id=\'menu-toggler\' data-target=\'#sidebar\'>");
document.writeln("					<span class=\'sr-only\'>Toggle sidebar</span>");
document.writeln("");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("				</button>");
document.writeln("");
document.writeln("				<div class=\'navbar-header pull-left\' style=\'width: 190px;border-right:1px solid #ccc;background-color: #E4E6E9;\'>");
document.writeln("					<a href=\'index.html\' class=\'navbar-brand\'>");
document.writeln("						<small>");
document.writeln("							<image src=\'assets/images/logo-03.png\' style=\'position: relative;left: 7px;top: 6px;height:80%;width:88%\'/>");
document.writeln("						</small>");
document.writeln("					</a>");
document.writeln("				</div>");
document.writeln("");
document.writeln("				<div class=\'navbar-header pull-left\' style=\'\'>");
document.writeln("							<div style=\'font-size: 24px;color:#fff;padding-left:14px;line-height: 57px;\'>新能源汽车“风光气储充”综合试验示范平台</div>");
document.writeln("				</div>");
document.writeln("");
document.writeln("				<div class=\'navbar-buttons navbar-header pull-right\' role=\'navigation\'>");
document.writeln("					<ul class=\'nav ace-nav\'>");
document.writeln("						<li class=\'light-blue dropdown-modal\' style=\'height: 57px;line-height: 57px;\'>");
document.writeln("							<a data-toggle=\'dropdown\' href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("								<img class=\'nav-user-photo\' src=\'resources/images/geren.png\' alt=\'Jason\'s Photo\' />");
document.writeln("								<span class=\'user-info\' style=\'top:11px;\'>");
document.writeln("									<small>您好,</small>");
document.writeln("                                  <span id=\"loginName\"></span>");
document.writeln("								</span>");
document.writeln("");
document.writeln("								<i class=\'ace-icon fa fa-caret-down\'></i>");
document.writeln("							</a>");
document.writeln("");
document.writeln("							<ul class=\'user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close\'>");
document.writeln("					");
document.writeln("								<li class=\'divider\'></li>");
document.writeln("");
document.writeln("								<li>");
document.writeln("									<a href=\'javascript:void(0)\' onclick=\'loginout();\'>");
document.writeln("										<i class=\'ace-icon fa fa-power-off\'></i>");
document.writeln("										退出");
document.writeln("									</a>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");