document.writeln("<div id=\'sidebar\' class=\'sidebar responsive ace-save-state\'>");
document.writeln("				<script type=\'text/javascript\'>");
document.writeln("					try{ace.settings.loadState(\'sidebar\')}catch(e){}");
document.writeln("				</script>");
document.writeln("");
document.writeln("				<ul class=\'nav nav-list\'>");
document.writeln("					<li class=\'active\'>");
document.writeln("						<a href=\'index.html\'>");
document.writeln("							<i class=\'menu-icon fa fa-tachometer\'></i>");
document.writeln("							<span class=\'menu-text\'> 首页 </span>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<b class=\'arrow\'></b>");
document.writeln("					</li>");
document.writeln("");
document.writeln("					<li class=\'\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("							<i class=\'menu-icon fa fa-desktop\'></i>");
document.writeln("							<span class=\'menu-text\'>");
document.writeln("								系统设置");
document.writeln("							</span>");
document.writeln("");
document.writeln("							<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<b class=\'arrow\'></b>");
document.writeln("");
document.writeln(" ");
document.writeln("");
document.writeln("						<ul class=\'submenu\'>");

document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("");
document.writeln("									用户管理");
document.writeln("									<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("								<ul class=\'submenu\'>");
document.writeln("									<!-- <li class=\'\'>");
document.writeln("										<a href=\'userType.html\'>");
document.writeln("											<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("											类型管理");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("									</li> -->");
document.writeln("	                               <li class=\'\'>");
document.writeln("										<a href=\'roleList.html\'>");
document.writeln("											<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("											角色管理");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("									</li>");
document.writeln("									<!-- <li class=\'\'>");
document.writeln("										<a href=\'power.html\'>");
document.writeln("											<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("											权限管理");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("									</li> -->");
document.writeln("");
document.writeln("									<li class=\'\'>");
document.writeln("										<a href=\'userList.html\'>");
document.writeln("											<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("											用户列表");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");

document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'stationList.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									站点列表");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("");
document.writeln("			 ");
document.writeln("");
document.writeln("		 ");
document.writeln("			 ");
document.writeln("				</ul><!-- /.nav-list -->");
document.writeln("");
document.writeln("				<div class=\'sidebar-toggle sidebar-collapse\' id=\'sidebar-collapse\'>");
document.writeln("					<i id=\'sidebar-toggle-icon\' class=\'ace-icon fa fa-angle-double-left ace-save-state\' data-icon1=\'ace-icon fa fa-angle-double-left\' data-icon2=\'ace-icon fa fa-angle-double-right\'></i>");
document.writeln("				</div>");
document.writeln("			</div>");